version: '3'

services:
  angular:
    container_name: sbrain-angular
    build: ./angular
    command: npm start
    volumes:
      - ./angular:/code
      - /usr/app/node_modules
    depends_on:
      - web
    ports:
      - "4200:4200"
      - "9876:9876"
    env_file: .env

  web:
    container_name: sbrain-django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/code
    env_file: .env

  postgres:
    container_name: sbrain-postgres
    restart: always
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres

