# Generated by Django 2.0 on 2018-03-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
