# Generated by Django 2.0 on 2018-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20180317_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeexpense',
            name='description',
        ),
        migrations.AddField(
            model_name='typeexpense',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
