# Generated by Django 2.0 on 2018-03-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20180317_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.CreditCard'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='file',
            field=models.FileField(blank=True, upload_to='income/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'cash'), (2, 'credit_card'), (3, 'check'), (4, 'bank_tranfer')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='file',
            field=models.FileField(blank=True, upload_to='income/'),
        ),
    ]
