# Generated by Django 2.0 on 2018-05-19 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20180320_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytypeexpense',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardbill',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typeexpense',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
            preserve_default=False,
        ),
    ]
