# Generated by Django 2.0 on 2018-06-10 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0012_auto_20180604_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.CreditCard'),
        ),
        migrations.AddField(
            model_name='installment',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'cash'), (2, 'credit_card'), (3, 'check'), (4, 'bank_tranfer')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='value',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
