# Generated by Django 2.0 on 2018-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20180604_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedication',
            name='comment',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
