# Generated by Django 2.0 on 2018-06-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('diary', '0007_auto_20180610_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dedication',
            name='comment',
        ),
        migrations.AddField(
            model_name='dedication',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
