# Generated by Django 2.0 on 2018-06-11 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20180610_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typededication',
            name='user',
        ),
        migrations.AlterField(
            model_name='dedication',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='dedication',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Role'),
        ),
        migrations.DeleteModel(
            name='TypeDedication',
        ),
    ]
