# Generated by Django 2.0 on 2018-06-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20180611_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
