# Generated by Django 2.0 on 2018-10-14 17:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0011_auto_20180611_0213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Habit',
        ),
        migrations.RenameModel(
            old_name='TypeTask',
            new_name='TypeHabit',
        ),
    ]
