# Generated by Django 2.0 on 2018-10-14 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_auto_20181014_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='typehabit',
            name='positive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
