# Generated by Django 2.0 on 2018-05-19 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_auto_20171212_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='phraseaudio',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='relationphrase',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='generator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generator',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phrase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phraseaudio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='production',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relationphrase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='season',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phraseaudio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relationphrase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
