# Generated by Django 2.0 on 2018-06-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20180519_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='generator',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='phraseaudio',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='producer',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='relationphrase',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
