# Generated by Django 2.0 on 2018-03-17 15:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20180317_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='expense',
            name='file',
            field=models.FileField(default='', upload_to='income/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='income',
            name='file',
            field=models.FileField(default='', upload_to='income/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='bill_day',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
    ]
